figures = [
    [
        ['oxx',
         'xxo',
         'ooo'],
        ['xoo',
         'xxo',
         'oxo']
    ],
    [
        ['xxo',
         'oxx',
         'ooo'],
        ['oxo',
         'xxo',
         'xoo']
    ],
    [
        ['xoo',
         'xxx',
         'ooo'],
        ['oxx',
         'oxo',
         'oxo'],
        ['xxx',
         'oox',
         'ooo'],
        ['oxo',
         'oxo',
         'xxo']
    ],
    [
        ['oox',
         'xxx',
         'ooo'],
        ['oxo',
         'oxo',
         'oxx'],
        ['xxx',
         'xoo',
         'ooo'],
        ['xxo',
         'oxo',
         'oxo']
    ],
    [
        ['ooxo',
         'ooxo',
         'ooxo',
         'ooxo'],
        ['oooo',
         'oooo',
         'xxxx',
         'oooo']
    ],
    [
        ['xx',
         'xx']
    ],
    [
        ['oxo',
         'xxx',
         'ooo'],
        ['oxo',
         'oxx',
         'oxo'],
        ['ooo',
         'xxx',
         'oxo'],
        ['oxo',
         'xxo',
         'oxo']
    ]
]
