figures = [
    [
        [
         'ooxxo',
         'oxxoo',
         'ooooo'],
        ['ooxoo',
         'ooxxo',
         'oooxo']
    ],
    [
        ['oxxoo',
         'ooxxo',
         'ooooo'],
        ['ooxoo',
         'oxxoo',
         'oxooo']
    ],
    [
        ['oxooo',
         'oxxxo',
         'ooooo'],
        ['ooxxo',
         'ooxoo',
         'ooxoo'],
        ['oxxxo',
         'oooxo',
         'ooooo'],
        ['ooxoo',
         'ooxoo',
         'oxxoo']
    ],
    [
        ['oooxo',
         'oxxxo',
         'ooooo',
         'ooooo'],
        ['ooxoo',
         'ooxoo',
         'ooxxo'],
        ['oxxxo',
         'oxooo',
         'ooooo'],
        ['oxxoo',
         'ooxoo',
         'ooxoo']
    ],
    [
        ['ooxoo',
         'ooxoo',
         'ooxoo',
         'ooxoo'],
        ['ooooo',
         'ooooo',
         'xxxxo',
         'ooooo']
    ],
    [
        ['xx',
         'xx']
    ],
    [
        ['ooxoo',
         'oxxxo',
         'ooooo',
         'ooooo'],
        ['ooooo',
         'ooxoo',
         'ooxxo',
         'ooxoo',
         'ooooo'],
        ['ooooo',
         'ooooo',
         'oxxxo',
         'ooxoo',
         'ooooo'],
        ['ooooo',
         'ooxoo',
         'oxxoo',
         'ooxoo',
         'ooooo']
    ]
]
